[package]
name = "coelp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ed25519-dalek = { version = "2.0", features = ["rand_core", "pem"] }
rand = "0.8.4"
pem = "3.0.2"
byteorder = "1.5.0"